apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-mydeployment
  labels:
    app: myapp
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      tier: frontend
  template:
    metadata:
      labels:
        app: myapp
        tier: frontend
    spec:
      containers:
      - name: sit737-week5
        image: hariprasadvenugopal/sit737-week5:1.1.1
        ports:
        - containerPort: 3080