apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: myapp
    tier: frontend
  ports:
  - name: myport
    port: 8037
    protocol: TCP
    targetPort: 3080
  type: LoadBalancer
  